apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: crud-app
        image: orlandonlyne/crud:31
        imagePullPolicy: Always  # Asegura que Kubernetes siempre descargue la última versión de la imagen
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
  namespace: default
spec:
  selector:
    app: crud-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080