apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # Permite crear un pod adicional temporalmente durante la actualización
      maxUnavailable: 0     # No permite que falte ningún pod disponible durante la actualización
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: crud-app
        image: orlandonlyne/crud:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
  namespace: default
spec:
  selector:
    app: crud-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080